---
title: 'EEB225 labs'
author: "Jeremy Gray"
---

EEB225 labs
========================================================
These labs were developed by Jeremy Gray for the course EEB225H1S -
Biostatistics for Biological Sciences at the University of Toronto for the
Winter term 2015.

They are targeted at students who have not seen R before and are headed into
an ecology major - so need to be conversant with basic R functions.

The labs follow a small lab experiment, where students planted Barley with and
without water and fertiliser, and put the data into excel with plots and T-tests.
The analyses carried out are on real data.

Lab4 introduces R, help, reading in data, subsetting and plotting.

Lab5 introduces Scripts, changing working directory and ANOVA.

lab6 introduces packages, ggplot2 and linear regression.

After working through the labs, students should know:

1. What R and RStudio are, how to download and run them
2. How to do basic math in the console
3. how to define objects (using <-)
4. How to use basic functions
5. How to get help
6. How to format data to load into R
7. How to load data into R
8. How to check our data is loaded in using head()
9. How to do basic plots
10. How to subset data
11. How to write and use basic R scripts
12. How to get and change our working directory
13. How to run and interpret an ANOVA
14. How the equation system works in R
15. How to install and load packages
16. The very basics of plotting with ggplot2
17. How to run and plot a linear regression
